apiVersion: v2
name: microservice
description: Helm chart for the FastAPI K8S microservice
type: application
version: 0.1.0          # version of the CHART itself
appVersion: "1.0.0"     # version of the APP it deploys